// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyTrackerSDK.proto

package tech.ubic.ed.mycomproxy.proto;

public final class MailTracker {
  private MailTracker() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_KeyValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_KeyValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_LaunchEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_LaunchEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_CustomEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_CustomEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_InstallEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_InstallEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_InstallEvent_AndroidData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_InstallEvent_AndroidData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_UpdateEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_UpdateEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_UpdateEvent_AndroidData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_UpdateEvent_AndroidData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_OldInstallReferrerEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_OldInstallReferrerEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_ApiInstallReferrerEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_ApiInstallReferrerEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_IadAttributionEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_IadAttributionEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_AuthEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_AuthEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_InviteEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_InviteEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_LevelEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_LevelEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_AdEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_AdEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_DeeplinkEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_DeeplinkEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_PurchaseEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_PurchaseEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_PurchaseEvent_AndroidData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_PurchaseEvent_AndroidData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_PurchaseEvent_IosData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_PurchaseEvent_IosData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_MiniAppEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_MiniAppEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_LightSensorEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_LightSensorEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_MagnetometerSensorEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_MagnetometerSensorEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_GyroscopeSensorEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_GyroscopeSensorEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_PressureSensorEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_PressureSensorEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_ProximitySensorEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_ProximitySensorEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Event_AdServicesAttributionEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Event_AdServicesAttributionEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Session_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Session_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Session_Period_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Session_Period_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_Settings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_Settings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_MrgsInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_MrgsInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_AppInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_AppInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_AppInfo_IosData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_AppInfo_IosData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_UserInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_UserInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_DeviceInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_DeviceInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_DeviceInfo_AndroidData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_DeviceInfo_AndroidData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_DeviceInfo_IosData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_DeviceInfo_IosData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_NetworkInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_NetworkInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_LocationInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_LocationInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_WifiInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_WifiInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_CellInfoCdma_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_CellInfoCdma_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_CellInfoGsm_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_CellInfoGsm_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_CellInfoLte_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_CellInfoLte_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_CellInfoWcdma_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_CellInfoWcdma_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_CellInfoTdscdma_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_CellInfoTdscdma_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_CellInfoNr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_CellInfoNr_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_CellInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_CellInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyTrackerSDK_PackageInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyTrackerSDK_PackageInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022MyTrackerSDK.proto\"\370C\n\014MyTrackerSDK\022\031\n" +
      "\021mytracker_version\030\001 \001(\014\022\016\n\006app_id\030\002 \001(\014" +
      "\022\026\n\016timestamp_base\030\003 \001(\004\022\026\n\016timestamp_se" +
      "nd\030\004 \001(\004\022\035\n\025custom_events_skipped\030\005 \001(\r\022" +
      "\023\n\013sha256_hash\030\006 \001(\014\022\024\n\014src_ip_chain\030\016 \003" +
      "(\007\022\021\n\ttimestamp\030\017 \001(\007\022\'\n\010app_info\030\025 \001(\0132" +
      "\025.MyTrackerSDK.AppInfo\022)\n\tuser_info\030\026 \001(" +
      "\0132\026.MyTrackerSDK.UserInfo\022-\n\013device_info" +
      "\030\027 \001(\0132\030.MyTrackerSDK.DeviceInfo\022)\n\tmrgs" +
      "_info\030\030 \001(\0132\026.MyTrackerSDK.MrgsInfo\022/\n\014n" +
      "etwork_info\030\031 \001(\0132\031.MyTrackerSDK.Network" +
      "Info\0221\n\rlocation_info\030\032 \001(\0132\032.MyTrackerS" +
      "DK.LocationInfo\022(\n\010settings\030\033 \001(\0132\026.MyTr" +
      "ackerSDK.Settings\022,\n\014wifi_current\030\034 \001(\0132" +
      "\026.MyTrackerSDK.WifiInfo\022+\n\013wifi_around\030\035" +
      " \003(\0132\026.MyTrackerSDK.WifiInfo\022$\n\004cell\030\036 \003" +
      "(\0132\026.MyTrackerSDK.CellInfo\022*\n\007package\030\037 " +
      "\003(\0132\031.MyTrackerSDK.PackageInfo\022-\n\tcdma_c" +
      "ell\030  \003(\0132\032.MyTrackerSDK.CellInfoCdma\022+\n" +
      "\010gsm_cell\030! \003(\0132\031.MyTrackerSDK.CellInfoG" +
      "sm\022+\n\010lte_cell\030\" \003(\0132\031.MyTrackerSDK.Cell" +
      "InfoLte\022/\n\nwcdma_cell\030# \003(\0132\033.MyTrackerS" +
      "DK.CellInfoWcdma\0223\n\014tdscdma_cell\030$ \003(\0132\035" +
      ".MyTrackerSDK.CellInfoTdscdma\022)\n\007nr_cell" +
      "\030% \003(\0132\030.MyTrackerSDK.CellInfoNr\022\"\n\005even" +
      "t\030) \003(\0132\023.MyTrackerSDK.Event\022&\n\007session\030" +
      "* \003(\0132\025.MyTrackerSDK.Session\032\361\037\n\005Event\022\022" +
      "\n\nevent_type\030\001 \001(\r\022\021\n\ttimestamp\030\002 \003(\005\022\032\n" +
      "\022timestamps_skipped\030\003 \001(\r\022/\n\006launch\030\013 \001(" +
      "\0132\037.MyTrackerSDK.Event.LaunchEvent\0221\n\007in" +
      "stall\030\014 \001(\0132 .MyTrackerSDK.Event.Install" +
      "Event\022I\n\024old_install_referrer\030\r \001(\0132+.My" +
      "TrackerSDK.Event.OldInstallReferrerEvent" +
      "\022I\n\024api_install_referrer\030\016 \001(\0132+.MyTrack" +
      "erSDK.Event.ApiInstallReferrerEvent\022@\n\017i" +
      "ad_attribution\030\017 \001(\0132\'.MyTrackerSDK.Even" +
      "t.IadAttributionEvent\0223\n\010deeplink\030\020 \001(\0132" +
      "!.MyTrackerSDK.Event.DeeplinkEvent\022/\n\006up" +
      "date\030\021 \001(\0132\037.MyTrackerSDK.Event.UpdateEv" +
      "ent\022,\n\005login\030\022 \001(\0132\035.MyTrackerSDK.Event." +
      "AuthEvent\0223\n\014registration\030\023 \001(\0132\035.MyTrac" +
      "kerSDK.Event.AuthEvent\022/\n\006invite\030\024 \001(\0132\037" +
      ".MyTrackerSDK.Event.InviteEvent\022-\n\005level" +
      "\030\025 \001(\0132\036.MyTrackerSDK.Event.LevelEvent\022/" +
      "\n\006custom\030\026 \001(\0132\037.MyTrackerSDK.Event.Cust" +
      "omEvent\0223\n\010purchase\030\027 \001(\0132!.MyTrackerSDK" +
      ".Event.PurchaseEvent\0222\n\rad_impression\030\031 " +
      "\001(\0132\033.MyTrackerSDK.Event.AdEvent\022-\n\010ad_c" +
      "lick\030\032 \001(\0132\033.MyTrackerSDK.Event.AdEvent\022" +
      "/\n\nad_revenue\030\033 \001(\0132\033.MyTrackerSDK.Event" +
      ".AdEvent\0227\n\rmini_app_open\030\034 \001(\0132 .MyTrac" +
      "kerSDK.Event.MiniAppEvent\0228\n\016mini_app_cl" +
      "ose\030\035 \001(\0132 .MyTrackerSDK.Event.MiniAppEv" +
      "ent\0228\n\016mini_app_login\030\036 \001(\0132 .MyTrackerS" +
      "DK.Event.MiniAppEvent\022?\n\025mini_app_regist" +
      "ration\030\037 \001(\0132 .MyTrackerSDK.Event.MiniAp" +
      "pEvent\0229\n\017mini_app_custom\030  \001(\0132 .MyTrac" +
      "kerSDK.Event.MiniAppEvent\022:\n\014light_senso" +
      "r\030! \001(\0132$.MyTrackerSDK.Event.LightSensor" +
      "Event\022H\n\023magnetometer_sensor\030\" \001(\0132+.MyT" +
      "rackerSDK.Event.MagnetometerSensorEvent\022" +
      "B\n\020gyroscope_sensor\030# \001(\0132(.MyTrackerSDK" +
      ".Event.GyroscopeSensorEvent\022@\n\017pressure_" +
      "sensor\030$ \001(\0132\'.MyTrackerSDK.Event.Pressu" +
      "reSensorEvent\022B\n\020proximity_sensor\030% \001(\0132" +
      "(.MyTrackerSDK.Event.ProximitySensorEven" +
      "t\022N\n\026ad_service_attribution\030& \001(\0132..MyTr" +
      "ackerSDK.Event.AdServicesAttributionEven" +
      "t\032j\n\010KeyValue\022\013\n\003key\030\001 \001(\014\022\024\n\014string_val" +
      "ue\030\002 \001(\014\022\021\n\tint_value\030\003 \001(\003\022\024\n\014double_va" +
      "lue\030\004 \001(\001\022\022\n\nbool_value\030\005 \001(\010\032\r\n\013LaunchE" +
      "vent\032I\n\013CustomEvent\022,\n\006params\030\001 \003(\0132\034.My" +
      "TrackerSDK.Event.KeyValue\022\014\n\004name\030\002 \001(\014\032" +
      "\342\001\n\014InstallEvent\022\032\n\022first_install_time\030\001" +
      " \001(\004\022B\n\014android_data\030\002 \001(\0132,.MyTrackerSD" +
      "K.Event.InstallEvent.AndroidData\032r\n\013Andr" +
      "oidData\022\021\n\tinstaller\030\001 \001(\014\022\031\n\021preinstall" +
      "_source\030\002 \001(\r\022\034\n\024preinstall_data_json\030\003 " +
      "\001(\014\022\027\n\017preinstall_file\030\004 \001(\014\032\314\001\n\013UpdateE" +
      "vent\022\023\n\013app_version\030\001 \001(\014\022\021\n\tapp_build\030\002" +
      " \001(\014\022\030\n\020from_app_version\030\003 \001(\014\022\026\n\016from_a" +
      "pp_build\030\004 \001(\014\022A\n\014android_data\030\005 \001(\0132+.M" +
      "yTrackerSDK.Event.UpdateEvent.AndroidDat" +
      "a\032 \n\013AndroidData\022\021\n\tinstaller\030\001 \001(\014\032>\n\027O" +
      "ldInstallReferrerEvent\022\020\n\010referrer\030\001 \001(\014" +
      "\022\021\n\tinstaller\030\002 \001(\014\032r\n\027ApiInstallReferre" +
      "rEvent\022\020\n\010referrer\030\001 \001(\014\022\021\n\tinstaller\030\002 " +
      "\001(\014\022\027\n\017click_timestamp\030\003 \001(\004\022\031\n\021install_" +
      "timestamp\030\004 \001(\004\032D\n\023IadAttributionEvent\022-" +
      "\n\007details\030\001 \003(\0132\034.MyTrackerSDK.Event.Key" +
      "Value\032h\n\tAuthEvent\022,\n\006params\030\001 \003(\0132\034.MyT" +
      "rackerSDK.Event.KeyValue\022\026\n\016custom_user_" +
      "id\030\002 \001(\014\022\025\n\rvk_connect_id\030\003 \001(\014\032;\n\013Invit" +
      "eEvent\022,\n\006params\030\001 \003(\0132\034.MyTrackerSDK.Ev" +
      "ent.KeyValue\032I\n\nLevelEvent\022,\n\006params\030\001 \003" +
      "(\0132\034.MyTrackerSDK.Event.KeyValue\022\r\n\005leve" +
      "l\030\002 \001(\005\032\207\001\n\007AdEvent\022\017\n\007network\030\001 \001(\r\022\017\n\007" +
      "revenue\030\002 \001(\014\022\025\n\rcurrency_code\030\003 \001(\014\022\016\n\006" +
      "source\030\004 \001(\014\022\024\n\014placement_id\030\005 \001(\014\022\r\n\005ad" +
      "_id\030\006 \001(\014\022\016\n\006format\030\007 \001(\014\0323\n\rDeeplinkEve" +
      "nt\022\020\n\010deeplink\030\001 \001(\014\022\020\n\010click_id\030\002 \001(\014\032\334" +
      "\004\n\rPurchaseEvent\022,\n\006params\030\001 \003(\0132\034.MyTra" +
      "ckerSDK.Event.KeyValue\022C\n\014android_data\030\002" +
      " \001(\0132-.MyTrackerSDK.Event.PurchaseEvent." +
      "AndroidData\022;\n\010ios_data\030\003 \001(\0132).MyTracke" +
      "rSDK.Event.PurchaseEvent.IosData\022\017\n\007reve" +
      "nue\030\004 \001(\014\022\025\n\rcurrency_code\030\005 \001(\014\032[\n\013Andr" +
      "oidData\022\032\n\022purchase_data_json\030\001 \001(\014\022\026\n\016d" +
      "ata_signature\030\002 \001(\014\022\030\n\020sku_details_json\030" +
      "\003 \001(\014\032\225\002\n\007IosData\022\022\n\nproduct_id\030\001 \001(\014\022\017\n" +
      "\007receipt\030\002 \001(\014\022\026\n\016transaction_id\030\003 \001(\014\022\037" +
      "\n\027original_transaction_id\030\004 \001(\014\022\r\n\005price" +
      "\030\013 \001(\014\022\032\n\022introductory_price\030\014 \001(\014\022\"\n\032in" +
      "troductory_currency_code\030\r \001(\014\022\024\n\014paymen" +
      "t_mode\030\016 \001(\r\022\031\n\021number_of_periods\030\017 \001(\004\022" +
      "\023\n\013period_unit\030\020 \001(\r\022\027\n\017number_of_units\030" +
      "\021 \001(\004\032\240\001\n\014MiniAppEvent\022,\n\006params\030\001 \003(\0132\034" +
      ".MyTrackerSDK.Event.KeyValue\022\023\n\013mini_app" +
      "_id\030\002 \001(\014\022\030\n\020platform_user_id\030\003 \001(\014\022\r\n\005q" +
      "uery\030\004 \001(\014\022\026\n\016custom_user_id\030\005 \001(\014\022\014\n\004na" +
      "me\030\006 \001(\014\032\"\n\020LightSensorEvent\022\016\n\006ml_lux\030\002" +
      " \001(\003\032C\n\027MagnetometerSensorEvent\022\014\n\004ml_x\030" +
      "\002 \001(\003\022\014\n\004ml_y\030\003 \001(\003\022\014\n\004ml_z\030\004 \001(\003\032@\n\024Gyr" +
      "oscopeSensorEvent\022\014\n\004ml_x\030\002 \001(\003\022\014\n\004ml_y\030" +
      "\003 \001(\003\022\014\n\004ml_z\030\004 \001(\003\032+\n\023PressureSensorEve" +
      "nt\022\024\n\014ml_millibars\030\002 \001(\003\032.\n\024ProximitySen" +
      "sorEvent\022\026\n\016ml_centimeters\030\002 \001(\003\032N\n\032AdSe" +
      "rvicesAttributionEvent\022\r\n\005token\030\001 \001(\014\022\r\n" +
      "\005error\030\002 \001(\014\022\022\n\nerror_code\030\003 \001(\005\032v\n\007Sess" +
      "ion\022,\n\006period\030\001 \003(\0132\034.MyTrackerSDK.Sessi" +
      "on.Period\022\027\n\017periods_skipped\030\002 \001(\r\032$\n\006Pe" +
      "riod\022\r\n\005start\030\001 \001(\005\022\013\n\003end\030\002 \001(\005\032\255\002\n\010Set" +
      "tings\022\027\n\017session_timeout\030\001 \001(\r\022\030\n\020locati" +
      "on_enabled\030\002 \001(\010\022\033\n\023environment_enabled\030" +
      "\003 \001(\010\022\026\n\016launch_enabled\030\004 \001(\010\022\030\n\020bufferi" +
      "ng_period\030\005 \001(\r\022\026\n\016forcing_period\030\006 \001(\r\022" +
      "%\n\035autotracking_purchase_enabled\030\007 \001(\010\022\032" +
      "\n\022preinstall_enabled\030\010 \001(\010\022%\n\035preinstall" +
      "_thirdparty_enabled\030\t \001(\010\022\035\n\025register_sk" +
      "ad_enabled\030\n \001(\010\032M\n\010MrgsInfo\022\023\n\013mrgs_app" +
      "_id\030\001 \001(\014\022\026\n\016mrgs_device_id\030\002 \001(\014\022\024\n\014mrg" +
      "s_user_id\030\003 \001(\014\032\314\001\n\007AppInfo\022\023\n\013app_versi" +
      "on\030\001 \001(\014\022\021\n\tapp_build\030\002 \001(\014\022\024\n\014app_langu" +
      "age\030\003 \001(\014\022\022\n\napp_bundle\030\004 \001(\014\022/\n\010ios_dat" +
      "a\030  \001(\0132\035.MyTrackerSDK.AppInfo.IosData\032>" +
      "\n\007IosData\022\025\n\rios_vendor_id\030\001 \001(\014\022\034\n\024ios_" +
      "vendor_id_cached\030\002 \001(\014\032\242\001\n\010UserInfo\022\016\n\006g" +
      "ender\030\001 \001(\r\022\013\n\003age\030\002 \001(\r\022\r\n\005ok_id\030\003 \003(\014\022" +
      "\r\n\005vk_id\030\004 \003(\014\022\r\n\005email\030\005 \003(\014\022\016\n\006icq_id\030" +
      "\006 \003(\014\022\026\n\016custom_user_id\030\007 \003(\014\022\r\n\005phone\030\010" +
      " \003(\014\022\025\n\rvk_connect_id\030\t \003(\014\032\340\006\n\nDeviceIn" +
      "fo\022\n\n\002os\030\001 \001(\r\022\022\n\nos_version\030\002 \001(\014\022\023\n\013os" +
      "_language\030\003 \001(\014\022\020\n\010timezone\030\004 \001(\014\022\023\n\013ins" +
      "tance_id\030\005 \001(\014\022\020\n\010codename\030\006 \001(\014\022\016\n\006euna" +
      "me\030\007 \001(\014\022\023\n\013manufacture\030\010 \001(\014\022\016\n\006rooted\030" +
      "\t \001(\010\022\024\n\014screen_width\030\n \001(\r\022\025\n\rscreen_he" +
      "ight\030\013 \001(\r\022\013\n\003dpi\030\014 \001(\r\022\014\n\004xdpi\030\r \001(\002\022\014\n" +
      "\004ydpi\030\016 \001(\002\022\017\n\007density\030\017 \001(\002\022\013\n\003mac\030\020 \001(" +
      "\014\022\026\n\016battery_status\030\021 \001(\r\022\025\n\rbattery_lev" +
      "el\030\022 \001(\r\022\024\n\014memory_total\030\023 \001(\004\022\030\n\020memory" +
      "_available\030\024 \001(\004\022\035\n\025external_memory_tota" +
      "l\030\025 \001(\004\022!\n\031external_memory_available\030\026 \001" +
      "(\004\022\023\n\013touchscreen\030\027 \001(\r\022\017\n\007ui_mode\030\030 \001(\r" +
      "\022 \n\030firebase_app_instance_id\030\031 \001(\014\022:\n\014an" +
      "droid_data\030\037 \001(\0132$.MyTrackerSDK.DeviceIn" +
      "fo.AndroidData\0222\n\010ios_data\030  \001(\0132 .MyTra" +
      "ckerSDK.DeviceInfo.IosData\032{\n\013AndroidDat" +
      "a\022\022\n\nandroid_id\030\001 \001(\014\022\014\n\004gaid\030\002 \001(\014\022\035\n\025g" +
      "aid_tracking_enabled\030\003 \001(\010\022\014\n\004oaid\030\004 \001(\014" +
      "\022\035\n\025oaid_tracking_enabled\030\005 \001(\010\032e\n\007IosDa" +
      "ta\022\014\n\004idfa\030\003 \001(\014\022\035\n\025idfa_tracking_enable" +
      "d\030\004 \001(\010\022\013\n\003sig\030\005 \001(\014\022\014\n\004sig2\030\006 \001(\014\022\022\n\nat" +
      "t_status\030\007 \001(\004\032\260\001\n\013NetworkInfo\022\022\n\nconnec" +
      "tion\030\001 \001(\r\022\027\n\017connection_type\030\002 \001(\014\022\024\n\014s" +
      "im_location\030\003 \001(\014\022\023\n\013operator_id\030\004 \001(\014\022\025" +
      "\n\roperator_name\030\005 \001(\014\022\027\n\017sim_operator_id" +
      "\030\006 \001(\014\022\031\n\021bluetooth_enabled\030\007 \001(\010\032y\n\014Loc" +
      "ationInfo\022\020\n\010latitude\030\001 \001(\001\022\021\n\tlongitude" +
      "\030\002 \001(\001\022\r\n\005speed\030\003 \001(\001\022\020\n\010accuracy\030\004 \001(\001\022" +
      "\021\n\ttimestamp\030\005 \001(\004\022\020\n\010provider\030\006 \001(\r\032[\n\010" +
      "WifiInfo\022\r\n\005bssid\030\001 \001(\014\022\014\n\004ssid\030\002 \001(\014\022\r\n" +
      "\005level\030\003 \001(\005\022\017\n\007wifi_id\030\005 \001(\r\022\022\n\nlink_sp" +
      "eed\030\006 \001(\r\032\354\001\n\014CellInfoCdma\022\022\n\nnetwork_id" +
      "\030\001 \001(\005\022\021\n\tsystem_id\030\002 \001(\005\022\027\n\017base_statio" +
      "n_id\030\003 \001(\005\022\013\n\003lat\030\004 \001(\005\022\013\n\003lon\030\005 \001(\005\022\022\n\n" +
      "cdma_level\030\006 \001(\005\022\020\n\010cdma_dbm\030\007 \001(\005\022\021\n\tcd" +
      "ma_ecio\030\010 \001(\005\022\022\n\nevdo_level\030\t \001(\005\022\020\n\010evd" +
      "o_dbm\030\n \001(\005\022\021\n\tevdo_ecio\030\013 \001(\005\022\020\n\010evdo_s" +
      "nr\030\014 \001(\005\032\222\001\n\013CellInfoGsm\022\013\n\003mcc\030\001 \001(\t\022\013\n" +
      "\003mnc\030\002 \001(\t\022\n\n\002ci\030\003 \001(\005\022\013\n\003lac\030\004 \001(\005\022\r\n\005a" +
      "rfcn\030\005 \001(\005\022\014\n\004bsic\030\006 \001(\005\022\r\n\005level\030\007 \001(\005\022" +
      "\013\n\003dbm\030\010 \001(\005\022\013\n\003asu\030\t \001(\005\022\n\n\002ta\030\n \001(\005\032\221\001" +
      "\n\013CellInfoLte\022\013\n\003mcc\030\001 \001(\t\022\013\n\003mnc\030\002 \001(\t\022" +
      "\n\n\002ci\030\003 \001(\005\022\013\n\003tac\030\004 \001(\005\022\r\n\005arfcn\030\005 \001(\005\022" +
      "\013\n\003pci\030\006 \001(\005\022\r\n\005level\030\007 \001(\005\022\013\n\003dbm\030\010 \001(\005" +
      "\022\013\n\003asu\030\t \001(\005\022\n\n\002ta\030\n \001(\005\032\207\001\n\rCellInfoWc" +
      "dma\022\013\n\003mcc\030\001 \001(\t\022\013\n\003mnc\030\002 \001(\t\022\n\n\002ci\030\003 \001(" +
      "\005\022\013\n\003lac\030\004 \001(\005\022\r\n\005arfcn\030\005 \001(\005\022\013\n\003psc\030\006 \001" +
      "(\005\022\r\n\005level\030\007 \001(\005\022\013\n\003dbm\030\010 \001(\005\022\013\n\003asu\030\t " +
      "\001(\005\032\211\001\n\017CellInfoTdscdma\022\013\n\003mcc\030\001 \001(\t\022\013\n\003" +
      "mnc\030\002 \001(\t\022\n\n\002ci\030\003 \001(\005\022\013\n\003lac\030\004 \001(\005\022\r\n\005ar" +
      "fcn\030\005 \001(\005\022\013\n\003cpi\030\006 \001(\005\022\r\n\005level\030\007 \001(\005\022\013\n" +
      "\003dbm\030\010 \001(\005\022\013\n\003asu\030\t \001(\005\032\204\001\n\nCellInfoNr\022\013" +
      "\n\003mcc\030\001 \001(\t\022\013\n\003mnc\030\002 \001(\t\022\n\n\002ci\030\003 \001(\003\022\013\n\003" +
      "tac\030\004 \001(\005\022\r\n\005arfcn\030\005 \001(\005\022\013\n\003pci\030\006 \001(\005\022\r\n" +
      "\005level\030\007 \001(\005\022\013\n\003dbm\030\010 \001(\005\022\013\n\003asu\030\t \001(\005\032\243" +
      "\003\n\010CellInfo\022\014\n\004type\030\001 \001(\014\022\r\n\005level\030\006 \001(\r" +
      "\022\013\n\003dbm\030\007 \001(\005\022\013\n\003asu\030\010 \001(\r\022\n\n\002ta\030\t \001(\r\022\017" +
      "\n\007cell_id\030\002 \001(\r\022\013\n\003lac\030\003 \001(\r\022\013\n\003mcc\030\004 \001(" +
      "\r\022\013\n\003mnc\030\005 \001(\r\022\014\n\004rfcn\030\n \001(\r\022\014\n\004bsic\030\013 \001" +
      "(\r\022\013\n\003psc\030\014 \001(\r\022\013\n\003tac\030\r \001(\r\022\022\n\nnetwork_" +
      "id\030\016 \001(\r\022\021\n\tsystem_id\030\017 \001(\r\022\027\n\017base_stat" +
      "ion_id\030\020 \001(\r\022\020\n\010cdma_lat\030\021 \001(\005\022\020\n\010cdma_l" +
      "on\030\022 \001(\005\022\022\n\ncdma_level\030\023 \001(\r\022\022\n\nevdo_lev" +
      "el\030\024 \001(\r\022\020\n\010cdma_dbm\030\025 \001(\005\022\020\n\010evdo_dbm\030\026" +
      " \001(\005\022\021\n\tevdo_ecio\030\027 \001(\r\022\021\n\tcdma_ecio\030\030 \001" +
      "(\r\022\020\n\010evdo_snr\030\031 \001(\r\0329\n\013PackageInfo\022\016\n\006b" +
      "undle\030\001 \001(\014\022\032\n\022first_install_time\030\002 \001(\004B" +
      ".\n\035tech.ubic.ed.mycomproxy.protoB\013MailTr" +
      "ackerP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MyTrackerSDK_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MyTrackerSDK_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_descriptor,
        new java.lang.String[] { "MytrackerVersion", "AppId", "TimestampBase", "TimestampSend", "CustomEventsSkipped", "Sha256Hash", "SrcIpChain", "Timestamp", "AppInfo", "UserInfo", "DeviceInfo", "MrgsInfo", "NetworkInfo", "LocationInfo", "Settings", "WifiCurrent", "WifiAround", "Cell", "Package", "CdmaCell", "GsmCell", "LteCell", "WcdmaCell", "TdscdmaCell", "NrCell", "Event", "Session", });
    internal_static_MyTrackerSDK_Event_descriptor =
      internal_static_MyTrackerSDK_descriptor.getNestedTypes().get(0);
    internal_static_MyTrackerSDK_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_descriptor,
        new java.lang.String[] { "EventType", "Timestamp", "TimestampsSkipped", "Launch", "Install", "OldInstallReferrer", "ApiInstallReferrer", "IadAttribution", "Deeplink", "Update", "Login", "Registration", "Invite", "Level", "Custom", "Purchase", "AdImpression", "AdClick", "AdRevenue", "MiniAppOpen", "MiniAppClose", "MiniAppLogin", "MiniAppRegistration", "MiniAppCustom", "LightSensor", "MagnetometerSensor", "GyroscopeSensor", "PressureSensor", "ProximitySensor", "AdServiceAttribution", });
    internal_static_MyTrackerSDK_Event_KeyValue_descriptor =
      internal_static_MyTrackerSDK_Event_descriptor.getNestedTypes().get(0);
    internal_static_MyTrackerSDK_Event_KeyValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_KeyValue_descriptor,
        new java.lang.String[] { "Key", "StringValue", "IntValue", "DoubleValue", "BoolValue", });
    internal_static_MyTrackerSDK_Event_LaunchEvent_descriptor =
      internal_static_MyTrackerSDK_Event_descriptor.getNestedTypes().get(1);
    internal_static_MyTrackerSDK_Event_LaunchEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_LaunchEvent_descriptor,
        new java.lang.String[] { });
    internal_static_MyTrackerSDK_Event_CustomEvent_descriptor =
      internal_static_MyTrackerSDK_Event_descriptor.getNestedTypes().get(2);
    internal_static_MyTrackerSDK_Event_CustomEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_CustomEvent_descriptor,
        new java.lang.String[] { "Params", "Name", });
    internal_static_MyTrackerSDK_Event_InstallEvent_descriptor =
      internal_static_MyTrackerSDK_Event_descriptor.getNestedTypes().get(3);
    internal_static_MyTrackerSDK_Event_InstallEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_InstallEvent_descriptor,
        new java.lang.String[] { "FirstInstallTime", "AndroidData", });
    internal_static_MyTrackerSDK_Event_InstallEvent_AndroidData_descriptor =
      internal_static_MyTrackerSDK_Event_InstallEvent_descriptor.getNestedTypes().get(0);
    internal_static_MyTrackerSDK_Event_InstallEvent_AndroidData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_InstallEvent_AndroidData_descriptor,
        new java.lang.String[] { "Installer", "PreinstallSource", "PreinstallDataJson", "PreinstallFile", });
    internal_static_MyTrackerSDK_Event_UpdateEvent_descriptor =
      internal_static_MyTrackerSDK_Event_descriptor.getNestedTypes().get(4);
    internal_static_MyTrackerSDK_Event_UpdateEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_UpdateEvent_descriptor,
        new java.lang.String[] { "AppVersion", "AppBuild", "FromAppVersion", "FromAppBuild", "AndroidData", });
    internal_static_MyTrackerSDK_Event_UpdateEvent_AndroidData_descriptor =
      internal_static_MyTrackerSDK_Event_UpdateEvent_descriptor.getNestedTypes().get(0);
    internal_static_MyTrackerSDK_Event_UpdateEvent_AndroidData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_UpdateEvent_AndroidData_descriptor,
        new java.lang.String[] { "Installer", });
    internal_static_MyTrackerSDK_Event_OldInstallReferrerEvent_descriptor =
      internal_static_MyTrackerSDK_Event_descriptor.getNestedTypes().get(5);
    internal_static_MyTrackerSDK_Event_OldInstallReferrerEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_OldInstallReferrerEvent_descriptor,
        new java.lang.String[] { "Referrer", "Installer", });
    internal_static_MyTrackerSDK_Event_ApiInstallReferrerEvent_descriptor =
      internal_static_MyTrackerSDK_Event_descriptor.getNestedTypes().get(6);
    internal_static_MyTrackerSDK_Event_ApiInstallReferrerEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_ApiInstallReferrerEvent_descriptor,
        new java.lang.String[] { "Referrer", "Installer", "ClickTimestamp", "InstallTimestamp", });
    internal_static_MyTrackerSDK_Event_IadAttributionEvent_descriptor =
      internal_static_MyTrackerSDK_Event_descriptor.getNestedTypes().get(7);
    internal_static_MyTrackerSDK_Event_IadAttributionEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_IadAttributionEvent_descriptor,
        new java.lang.String[] { "Details", });
    internal_static_MyTrackerSDK_Event_AuthEvent_descriptor =
      internal_static_MyTrackerSDK_Event_descriptor.getNestedTypes().get(8);
    internal_static_MyTrackerSDK_Event_AuthEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_AuthEvent_descriptor,
        new java.lang.String[] { "Params", "CustomUserId", "VkConnectId", });
    internal_static_MyTrackerSDK_Event_InviteEvent_descriptor =
      internal_static_MyTrackerSDK_Event_descriptor.getNestedTypes().get(9);
    internal_static_MyTrackerSDK_Event_InviteEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_InviteEvent_descriptor,
        new java.lang.String[] { "Params", });
    internal_static_MyTrackerSDK_Event_LevelEvent_descriptor =
      internal_static_MyTrackerSDK_Event_descriptor.getNestedTypes().get(10);
    internal_static_MyTrackerSDK_Event_LevelEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_LevelEvent_descriptor,
        new java.lang.String[] { "Params", "Level", });
    internal_static_MyTrackerSDK_Event_AdEvent_descriptor =
      internal_static_MyTrackerSDK_Event_descriptor.getNestedTypes().get(11);
    internal_static_MyTrackerSDK_Event_AdEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_AdEvent_descriptor,
        new java.lang.String[] { "Network", "Revenue", "CurrencyCode", "Source", "PlacementId", "AdId", "Format", });
    internal_static_MyTrackerSDK_Event_DeeplinkEvent_descriptor =
      internal_static_MyTrackerSDK_Event_descriptor.getNestedTypes().get(12);
    internal_static_MyTrackerSDK_Event_DeeplinkEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_DeeplinkEvent_descriptor,
        new java.lang.String[] { "Deeplink", "ClickId", });
    internal_static_MyTrackerSDK_Event_PurchaseEvent_descriptor =
      internal_static_MyTrackerSDK_Event_descriptor.getNestedTypes().get(13);
    internal_static_MyTrackerSDK_Event_PurchaseEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_PurchaseEvent_descriptor,
        new java.lang.String[] { "Params", "AndroidData", "IosData", "Revenue", "CurrencyCode", });
    internal_static_MyTrackerSDK_Event_PurchaseEvent_AndroidData_descriptor =
      internal_static_MyTrackerSDK_Event_PurchaseEvent_descriptor.getNestedTypes().get(0);
    internal_static_MyTrackerSDK_Event_PurchaseEvent_AndroidData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_PurchaseEvent_AndroidData_descriptor,
        new java.lang.String[] { "PurchaseDataJson", "DataSignature", "SkuDetailsJson", });
    internal_static_MyTrackerSDK_Event_PurchaseEvent_IosData_descriptor =
      internal_static_MyTrackerSDK_Event_PurchaseEvent_descriptor.getNestedTypes().get(1);
    internal_static_MyTrackerSDK_Event_PurchaseEvent_IosData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_PurchaseEvent_IosData_descriptor,
        new java.lang.String[] { "ProductId", "Receipt", "TransactionId", "OriginalTransactionId", "Price", "IntroductoryPrice", "IntroductoryCurrencyCode", "PaymentMode", "NumberOfPeriods", "PeriodUnit", "NumberOfUnits", });
    internal_static_MyTrackerSDK_Event_MiniAppEvent_descriptor =
      internal_static_MyTrackerSDK_Event_descriptor.getNestedTypes().get(14);
    internal_static_MyTrackerSDK_Event_MiniAppEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_MiniAppEvent_descriptor,
        new java.lang.String[] { "Params", "MiniAppId", "PlatformUserId", "Query", "CustomUserId", "Name", });
    internal_static_MyTrackerSDK_Event_LightSensorEvent_descriptor =
      internal_static_MyTrackerSDK_Event_descriptor.getNestedTypes().get(15);
    internal_static_MyTrackerSDK_Event_LightSensorEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_LightSensorEvent_descriptor,
        new java.lang.String[] { "MlLux", });
    internal_static_MyTrackerSDK_Event_MagnetometerSensorEvent_descriptor =
      internal_static_MyTrackerSDK_Event_descriptor.getNestedTypes().get(16);
    internal_static_MyTrackerSDK_Event_MagnetometerSensorEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_MagnetometerSensorEvent_descriptor,
        new java.lang.String[] { "MlX", "MlY", "MlZ", });
    internal_static_MyTrackerSDK_Event_GyroscopeSensorEvent_descriptor =
      internal_static_MyTrackerSDK_Event_descriptor.getNestedTypes().get(17);
    internal_static_MyTrackerSDK_Event_GyroscopeSensorEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_GyroscopeSensorEvent_descriptor,
        new java.lang.String[] { "MlX", "MlY", "MlZ", });
    internal_static_MyTrackerSDK_Event_PressureSensorEvent_descriptor =
      internal_static_MyTrackerSDK_Event_descriptor.getNestedTypes().get(18);
    internal_static_MyTrackerSDK_Event_PressureSensorEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_PressureSensorEvent_descriptor,
        new java.lang.String[] { "MlMillibars", });
    internal_static_MyTrackerSDK_Event_ProximitySensorEvent_descriptor =
      internal_static_MyTrackerSDK_Event_descriptor.getNestedTypes().get(19);
    internal_static_MyTrackerSDK_Event_ProximitySensorEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_ProximitySensorEvent_descriptor,
        new java.lang.String[] { "MlCentimeters", });
    internal_static_MyTrackerSDK_Event_AdServicesAttributionEvent_descriptor =
      internal_static_MyTrackerSDK_Event_descriptor.getNestedTypes().get(20);
    internal_static_MyTrackerSDK_Event_AdServicesAttributionEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Event_AdServicesAttributionEvent_descriptor,
        new java.lang.String[] { "Token", "Error", "ErrorCode", });
    internal_static_MyTrackerSDK_Session_descriptor =
      internal_static_MyTrackerSDK_descriptor.getNestedTypes().get(1);
    internal_static_MyTrackerSDK_Session_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Session_descriptor,
        new java.lang.String[] { "Period", "PeriodsSkipped", });
    internal_static_MyTrackerSDK_Session_Period_descriptor =
      internal_static_MyTrackerSDK_Session_descriptor.getNestedTypes().get(0);
    internal_static_MyTrackerSDK_Session_Period_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Session_Period_descriptor,
        new java.lang.String[] { "Start", "End", });
    internal_static_MyTrackerSDK_Settings_descriptor =
      internal_static_MyTrackerSDK_descriptor.getNestedTypes().get(2);
    internal_static_MyTrackerSDK_Settings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_Settings_descriptor,
        new java.lang.String[] { "SessionTimeout", "LocationEnabled", "EnvironmentEnabled", "LaunchEnabled", "BufferingPeriod", "ForcingPeriod", "AutotrackingPurchaseEnabled", "PreinstallEnabled", "PreinstallThirdpartyEnabled", "RegisterSkadEnabled", });
    internal_static_MyTrackerSDK_MrgsInfo_descriptor =
      internal_static_MyTrackerSDK_descriptor.getNestedTypes().get(3);
    internal_static_MyTrackerSDK_MrgsInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_MrgsInfo_descriptor,
        new java.lang.String[] { "MrgsAppId", "MrgsDeviceId", "MrgsUserId", });
    internal_static_MyTrackerSDK_AppInfo_descriptor =
      internal_static_MyTrackerSDK_descriptor.getNestedTypes().get(4);
    internal_static_MyTrackerSDK_AppInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_AppInfo_descriptor,
        new java.lang.String[] { "AppVersion", "AppBuild", "AppLanguage", "AppBundle", "IosData", });
    internal_static_MyTrackerSDK_AppInfo_IosData_descriptor =
      internal_static_MyTrackerSDK_AppInfo_descriptor.getNestedTypes().get(0);
    internal_static_MyTrackerSDK_AppInfo_IosData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_AppInfo_IosData_descriptor,
        new java.lang.String[] { "IosVendorId", "IosVendorIdCached", });
    internal_static_MyTrackerSDK_UserInfo_descriptor =
      internal_static_MyTrackerSDK_descriptor.getNestedTypes().get(5);
    internal_static_MyTrackerSDK_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_UserInfo_descriptor,
        new java.lang.String[] { "Gender", "Age", "OkId", "VkId", "Email", "IcqId", "CustomUserId", "Phone", "VkConnectId", });
    internal_static_MyTrackerSDK_DeviceInfo_descriptor =
      internal_static_MyTrackerSDK_descriptor.getNestedTypes().get(6);
    internal_static_MyTrackerSDK_DeviceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_DeviceInfo_descriptor,
        new java.lang.String[] { "Os", "OsVersion", "OsLanguage", "Timezone", "InstanceId", "Codename", "Euname", "Manufacture", "Rooted", "ScreenWidth", "ScreenHeight", "Dpi", "Xdpi", "Ydpi", "Density", "Mac", "BatteryStatus", "BatteryLevel", "MemoryTotal", "MemoryAvailable", "ExternalMemoryTotal", "ExternalMemoryAvailable", "Touchscreen", "UiMode", "FirebaseAppInstanceId", "AndroidData", "IosData", });
    internal_static_MyTrackerSDK_DeviceInfo_AndroidData_descriptor =
      internal_static_MyTrackerSDK_DeviceInfo_descriptor.getNestedTypes().get(0);
    internal_static_MyTrackerSDK_DeviceInfo_AndroidData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_DeviceInfo_AndroidData_descriptor,
        new java.lang.String[] { "AndroidId", "Gaid", "GaidTrackingEnabled", "Oaid", "OaidTrackingEnabled", });
    internal_static_MyTrackerSDK_DeviceInfo_IosData_descriptor =
      internal_static_MyTrackerSDK_DeviceInfo_descriptor.getNestedTypes().get(1);
    internal_static_MyTrackerSDK_DeviceInfo_IosData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_DeviceInfo_IosData_descriptor,
        new java.lang.String[] { "Idfa", "IdfaTrackingEnabled", "Sig", "Sig2", "AttStatus", });
    internal_static_MyTrackerSDK_NetworkInfo_descriptor =
      internal_static_MyTrackerSDK_descriptor.getNestedTypes().get(7);
    internal_static_MyTrackerSDK_NetworkInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_NetworkInfo_descriptor,
        new java.lang.String[] { "Connection", "ConnectionType", "SimLocation", "OperatorId", "OperatorName", "SimOperatorId", "BluetoothEnabled", });
    internal_static_MyTrackerSDK_LocationInfo_descriptor =
      internal_static_MyTrackerSDK_descriptor.getNestedTypes().get(8);
    internal_static_MyTrackerSDK_LocationInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_LocationInfo_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", "Speed", "Accuracy", "Timestamp", "Provider", });
    internal_static_MyTrackerSDK_WifiInfo_descriptor =
      internal_static_MyTrackerSDK_descriptor.getNestedTypes().get(9);
    internal_static_MyTrackerSDK_WifiInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_WifiInfo_descriptor,
        new java.lang.String[] { "Bssid", "Ssid", "Level", "WifiId", "LinkSpeed", });
    internal_static_MyTrackerSDK_CellInfoCdma_descriptor =
      internal_static_MyTrackerSDK_descriptor.getNestedTypes().get(10);
    internal_static_MyTrackerSDK_CellInfoCdma_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_CellInfoCdma_descriptor,
        new java.lang.String[] { "NetworkId", "SystemId", "BaseStationId", "Lat", "Lon", "CdmaLevel", "CdmaDbm", "CdmaEcio", "EvdoLevel", "EvdoDbm", "EvdoEcio", "EvdoSnr", });
    internal_static_MyTrackerSDK_CellInfoGsm_descriptor =
      internal_static_MyTrackerSDK_descriptor.getNestedTypes().get(11);
    internal_static_MyTrackerSDK_CellInfoGsm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_CellInfoGsm_descriptor,
        new java.lang.String[] { "Mcc", "Mnc", "Ci", "Lac", "Arfcn", "Bsic", "Level", "Dbm", "Asu", "Ta", });
    internal_static_MyTrackerSDK_CellInfoLte_descriptor =
      internal_static_MyTrackerSDK_descriptor.getNestedTypes().get(12);
    internal_static_MyTrackerSDK_CellInfoLte_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_CellInfoLte_descriptor,
        new java.lang.String[] { "Mcc", "Mnc", "Ci", "Tac", "Arfcn", "Pci", "Level", "Dbm", "Asu", "Ta", });
    internal_static_MyTrackerSDK_CellInfoWcdma_descriptor =
      internal_static_MyTrackerSDK_descriptor.getNestedTypes().get(13);
    internal_static_MyTrackerSDK_CellInfoWcdma_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_CellInfoWcdma_descriptor,
        new java.lang.String[] { "Mcc", "Mnc", "Ci", "Lac", "Arfcn", "Psc", "Level", "Dbm", "Asu", });
    internal_static_MyTrackerSDK_CellInfoTdscdma_descriptor =
      internal_static_MyTrackerSDK_descriptor.getNestedTypes().get(14);
    internal_static_MyTrackerSDK_CellInfoTdscdma_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_CellInfoTdscdma_descriptor,
        new java.lang.String[] { "Mcc", "Mnc", "Ci", "Lac", "Arfcn", "Cpi", "Level", "Dbm", "Asu", });
    internal_static_MyTrackerSDK_CellInfoNr_descriptor =
      internal_static_MyTrackerSDK_descriptor.getNestedTypes().get(15);
    internal_static_MyTrackerSDK_CellInfoNr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_CellInfoNr_descriptor,
        new java.lang.String[] { "Mcc", "Mnc", "Ci", "Tac", "Arfcn", "Pci", "Level", "Dbm", "Asu", });
    internal_static_MyTrackerSDK_CellInfo_descriptor =
      internal_static_MyTrackerSDK_descriptor.getNestedTypes().get(16);
    internal_static_MyTrackerSDK_CellInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_CellInfo_descriptor,
        new java.lang.String[] { "Type", "Level", "Dbm", "Asu", "Ta", "CellId", "Lac", "Mcc", "Mnc", "Rfcn", "Bsic", "Psc", "Tac", "NetworkId", "SystemId", "BaseStationId", "CdmaLat", "CdmaLon", "CdmaLevel", "EvdoLevel", "CdmaDbm", "EvdoDbm", "EvdoEcio", "CdmaEcio", "EvdoSnr", });
    internal_static_MyTrackerSDK_PackageInfo_descriptor =
      internal_static_MyTrackerSDK_descriptor.getNestedTypes().get(17);
    internal_static_MyTrackerSDK_PackageInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyTrackerSDK_PackageInfo_descriptor,
        new java.lang.String[] { "Bundle", "FirstInstallTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
